#!/bin/sh
#

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

branchPath=$(git symbolic-ref -q HEAD)
branchName=${branchPath##*/}

if [ -n "$branchName" ]; then
    echo "$branchName | $(cat $1)" > $1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
