#!/usr/local/bin/bash
set -u

_URL=https://github.com

LOG() {
	echo "$*" >&2
}

START="$(cd .. && pwd)"

find -L $START -type d -depth 1					|\
grep -v -E "github.io|\/.git|.vscode\b"			|\
sort											|\
while read _THISREP
do
	_REP="$(basename "$_THISREP")"	# Learning-TypeScript_DataStructures-and-Algorithms-01
	_TMP="${_REP%%_*}"				# Learning-TypeScript

	_DIR="$_THISREP"
	if [[ -L "$_THISREP" ]]; then
		_DIR="$(readlink -n "$_THISREP")"
		_DIR="$(cd "$(dirname "$START/$_DIR")" && pwd)/$_REP"
	fi

	_DIR="${_DIR#*repositories/}"

	#
	_SUB="${_REP#*_}"				# DataStructures-and-Algorithms-01
	_SUB="${_SUB//-/ }"				# DataStructures and Algorithms 01
	_SUB="${_SUB//_/ }"				# DataStructures and Algorithms 01

	_TYP="${_TMP%%-*}"
	_LNG="${_TMP#*-}"
	_LNG="${_LNG,,}"

	#
	_USR="$(dirname "$_DIR")"

	#
	_TXT=""
	[[ -f "$_THISREP/DESCRIPTION" ]]		&& _TXT=$(cat "$_THISREP/DESCRIPTION" | sed '1,$s/$/\<br\>/g')

	[[ "$_LNG" = "" ]]						&& _LNG="default"

	if [[ "$_TYP" = "$_LNG" ]]; then
		_HDR="$_TYP"
	else
		_HDR="$_TYP $_LNG"
	fi

	_HDR="$_TYP"

	#
	_DBG=

	#
	[[ "$_HDR" == "Working" ]] && set -x

	#
	_CAT="${_HDR,,}"
	[[ "learning"		=~ "$_CAT"		]] && _CAT=learn			&& _DBG=${_DBG}l
	[[ "koans|test"		=~ "$_CAT"		]] && _CAT=test				&& _DBG=${_DBG}k
	[[ "course|working"	=~ "$_CAT"		]] && _CAT=practice			&& _DBG=${_DBG}c
	[[ "workshop"		=~ "$_CAT"		]] && _CAT=practice			&& _DBG=${_DBG}w
	[[ "missing"		=~ "$_CAT"		]] && _CAT=default			&& _DBG=${_DBG}m
	[[ "theme"			=~ "$_CAT"		]] && _CAT=bootstrap		&& _DBG=${_DBG}t

	_IMG="missing.png"
	[[ -f "assets/img/${_CAT}.png"		]] && _IMG=${_CAT}.png		&& _DBG=${_DBG}_1
	[[ -f "assets/img/${_HDR,,}.png"	]] && _IMG=${_HDR,,}.png	&& _DBG=${_DBG}_2
	[[ -f "assets/img/${_LNG}.png"		]] && _IMG=${_LNG}.png		&& _DBG=${_DBG}_3

	#
	[[ "$_HDR" == "Working" ]] && set +x

	#
	_LNK="$_URL/$_USR/$_REP"

	#
	echo "- title: \"$_HDR\""
	echo "  subtitle: \"$_SUB\""
	echo "  text: \"$_TXT\""
	echo "  link: $_LNK"
	echo "  lang: $_LNG"
	echo "  img: ${_IMG,,}"
	echo "  category: ${_CAT}"
	#echo "  rep: ${_THISREP}"
	#echo "  dir: ${_DIR}"
	#echo "  usr: ${_USR/\.\.\//}"
	echo "  summary: C=$_CAT | I=$_IMG | T=$_HDR | S=$_SUB | R=$_REP | DEBUG=$_DBG"
	echo ""
	echo "#"

	# LOG "$_THISREP | DIR=$_DIR USR=$_USR REP=$_REP LINK=$_LNK CAT=$_CAT"

done  > _data/repositories.yml